name: CI
on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install 3rd party things
        run: |
          sudo apt-get update
          sudo apt-get install valgrind
      - name: build everything
        run: |
          $CC -o nob nob.c
          ./nob valgrind
        env:
          CC: gcc
          CXX: g++
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install 3rd party things
        run: |
          sudo apt-get update
          sudo apt-get install valgrind
      - name: build everything
        run: |
          $CC -o nob nob.c
          ./nob valgrind
        env:
          CC: clang
          CXX: clang++
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: build everything
        run: |
          $CC -o nob nob.c
          ./nob run
        env:
          CC: clang
          CXX: clang++